/**
 * Cirius Deploy — Handles GitHub, Vercel, Netlify, Supabase deploys
 * Actions: github, vercel, netlify, supabase
 * Vercel: uploads files directly via Deployments API for instant preview URLs
 */
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status, headers: { ...CORS, "Content-Type": "application/json" },
  });
}

async function getUser(req: Request) {
  const auth = req.headers.get("Authorization") || "";
  if (!auth.startsWith("Bearer ")) return null;
  const sc = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_ANON_KEY")!,
    { global: { headers: { Authorization: auth } } }
  );
  const { data: { user } } = await sc.auth.getUser();
  return user;
}

async function logDeploy(sc: ReturnType<typeof createClient>, projectId: string, step: string, status: string, message: string) {
  await sc.from("cirius_generation_log").insert({
    project_id: projectId, step, status, message,
    level: status === "failed" ? "error" : "info",
  });
}

async function getIntegration(sc: ReturnType<typeof createClient>, userId: string, provider: string) {
  const { data } = await sc.from("cirius_integrations")
    .select("*").eq("user_id", userId).eq("provider", provider).eq("is_active", true).maybeSingle();
  return data;
}

/** Convert UTF-8 string to SHA1 hex (for Vercel file upload) */
async function sha1Hex(content: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(content);
  const hashBuffer = await crypto.subtle.digest("SHA-1", data);
  return Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, "0")).join("");
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: CORS });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  const user = await getUser(req);
  const authHeader = req.headers.get("Authorization") || "";
  const isServiceKey = authHeader === `Bearer ${Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")}`;
  if (!user && !isServiceKey) return json({ error: "Unauthorized" }, 401);

  const sc = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const body = await req.json().catch(() => ({}));
  const action = (body.action as string) || "";
  const projectId = (body.project_id as string) || "";

  if (!projectId) return json({ error: "project_id required" }, 400);

  let projectQuery = sc.from("cirius_projects").select("*").eq("id", projectId);
  if (user) projectQuery = projectQuery.eq("user_id", user.id);
  const { data: project } = await projectQuery.single();
  if (!project) return json({ error: "Project not found" }, 404);
  const projectUserId = project.user_id as string;

  const filesJson = (project.source_files_json || {}) as Record<string, string>;
  if (Object.keys(filesJson).length === 0) return json({ error: "No source files to deploy" }, 400);

  await sc.from("cirius_projects").update({ status: "deploying" }).eq("id", projectId);

  // ─── GITHUB ───
  if (action === "github") {
    const integration = await getIntegration(sc, projectUserId, "github");
    if (!integration?.access_token_enc) return json({ error: "GitHub not connected. Connect via integrations page." }, 400);

    const ghToken = integration.access_token_enc;
    const repoName = project.name.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-").slice(0, 50);

    await logDeploy(sc, projectId, "deploy_github", "started", "Criando repositório...");

    try {
      const createRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: { Authorization: `Bearer ${ghToken}`, "Content-Type": "application/json", "User-Agent": "Cirius-Starble" },
        body: JSON.stringify({ name: repoName, private: false, auto_init: true, description: `Generated by Cirius — ${project.description || ""}` }),
      });

      let repoData: any;
      if (createRes.status === 422) {
        const userRes = await fetch("https://api.github.com/user", {
          headers: { Authorization: `Bearer ${ghToken}`, "User-Agent": "Cirius-Starble" },
        });
        const userData = await userRes.json();
        const owner = userData.login;
        const getRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}`, {
          headers: { Authorization: `Bearer ${ghToken}`, "User-Agent": "Cirius-Starble" },
        });
        if (!getRes.ok) {
          await getRes.text().catch(() => {});
          return json({ error: "Repository creation failed" }, 500);
        }
        repoData = await getRes.json();
      } else if (!createRes.ok) {
        await createRes.text().catch(() => {});
        return json({ error: "Repository creation failed" }, 500);
      } else {
        repoData = await createRes.json();
      }

      const owner = repoData.owner?.login || repoData.full_name?.split("/")[0];
      const repo = repoData.name;
      let pushed = 0;

      for (const [path, content] of Object.entries(filesJson)) {
        if (typeof content !== "string") continue;

        const existRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}?ref=main`, {
          headers: { Authorization: `Bearer ${ghToken}`, "User-Agent": "Cirius-Starble" },
        });
        let sha: string | undefined;
        if (existRes.ok) {
          const existing = await existRes.json();
          sha = existing.sha;
        } else {
          await existRes.text().catch(() => {});
        }

        const putRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
          method: "PUT",
          headers: { Authorization: `Bearer ${ghToken}`, "Content-Type": "application/json", "User-Agent": "Cirius-Starble" },
          body: JSON.stringify({
            message: `feat: Cirius initial build — ${path}`,
            content: btoa(unescape(encodeURIComponent(content))),
            branch: "main",
            ...(sha ? { sha } : {}),
          }),
        });

        if (putRes.ok) pushed++;
        else await putRes.text().catch(() => {});
      }

      const repoUrl = `https://github.com/${owner}/${repo}`;
      await sc.from("cirius_projects").update({
        github_repo: `${owner}/${repo}`, github_url: repoUrl,
        status: "live", deployed_at: new Date().toISOString(),
        current_step: "done", progress_pct: 100,
        generation_ended_at: new Date().toISOString(),
      }).eq("id", projectId);

      await logDeploy(sc, projectId, "deploy_github", "completed", `${pushed} arquivos pushados para ${repoUrl}`);

      // Chain: auto-deploy to Netlify first (primary), then Vercel as fallback
      const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
      const svcKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
      const netlifyIntegration = await getIntegration(sc, projectUserId, "netlify");
      if (netlifyIntegration?.access_token_enc) {
        fetch(`${supabaseUrl}/functions/v1/cirius-deploy`, {
          method: "POST",
          headers: { Authorization: `Bearer ${svcKey}`, "Content-Type": "application/json" },
          body: JSON.stringify({ action: "netlify", project_id: projectId }),
        }).catch(console.error);
      } else {
        // Fallback to Vercel if Netlify not connected
        const vercelIntegration = await getIntegration(sc, projectUserId, "vercel");
        if (vercelIntegration?.access_token_enc) {
          fetch(`${supabaseUrl}/functions/v1/cirius-deploy`, {
            method: "POST",
            headers: { Authorization: `Bearer ${svcKey}`, "Content-Type": "application/json" },
            body: JSON.stringify({ action: "vercel", project_id: projectId }),
          }).catch(console.error);
        }
      }

      return json({ repo_url: repoUrl, files_pushed: pushed });
    } catch (e) {
      console.error("[cirius-deploy] github error:", (e as Error).message);
      await logDeploy(sc, projectId, "deploy_github", "failed", "GitHub deploy failed");
      return json({ error: "GitHub deploy failed" }, 500);
    }
  }

  // ─── VERCEL — Direct file upload deployment ───
  if (action === "vercel") {
    const integration = await getIntegration(sc, projectUserId, "vercel");
    if (!integration?.access_token_enc) return json({ error: "Vercel not connected" }, 400);

    const vToken = integration.access_token_enc;
    const teamId = integration.account_id || undefined;
    await logDeploy(sc, projectId, "deploy_vercel", "started", "Enviando arquivos para Vercel...");

    try {
      const projectSlug = project.name.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-").slice(0, 50);

      // Step 1: Ensure Vercel project exists (create if needed)
      const teamQuery = teamId ? `?teamId=${teamId}` : "";
      let vercelProjectId = project.vercel_project_id;

      if (!vercelProjectId) {
        // Try to create project
        const cpRes = await fetch(`https://api.vercel.com/v9/projects${teamQuery}`, {
          method: "POST",
          headers: { Authorization: `Bearer ${vToken}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            name: projectSlug,
            framework: "vite",
            ...(project.github_repo ? { gitRepository: { type: "github", repo: project.github_repo } } : {}),
          }),
        });
        const cpData = await cpRes.json();
        if (cpRes.ok || cpData?.id) {
          vercelProjectId = cpData.id;
        } else if (cpRes.status === 409 || cpData?.error?.code === "project_already_exists") {
          // Project exists, fetch it
          const gpRes = await fetch(`https://api.vercel.com/v9/projects/${projectSlug}${teamQuery}`, {
            headers: { Authorization: `Bearer ${vToken}` },
          });
          const gpData = await gpRes.json();
          vercelProjectId = gpData?.id;
        }

        if (!vercelProjectId) {
          await logDeploy(sc, projectId, "deploy_vercel", "failed", "Could not create/find Vercel project");
          return json({ error: "Vercel project creation failed" }, 500);
        }
      }

      // Step 2: Upload all files to Vercel
      const fileEntries: { file: string; sha: string; size: number }[] = [];
      const encoder = new TextEncoder();

      for (const [path, content] of Object.entries(filesJson)) {
        if (typeof content !== "string") continue;
        const sha = await sha1Hex(content);
        const size = encoder.encode(content).length;
        fileEntries.push({ file: path, sha, size });

        // Upload each file individually
        const uploadRes = await fetch(`https://api.vercel.com/v2/files${teamQuery}`, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${vToken}`,
            "Content-Type": "application/octet-stream",
            "x-vercel-digest": sha,
            "x-vercel-size": String(size),
          },
          body: encoder.encode(content),
        });

        if (!uploadRes.ok && uploadRes.status !== 409) {
          // 409 = file already exists (fine)
          const errText = await uploadRes.text().catch(() => "");
          console.error(`[cirius-deploy] file upload failed: ${path} — ${uploadRes.status} ${errText}`);
        }
      }

      // Step 3: Create deployment with all files
      const deployPayload: any = {
        name: projectSlug,
        files: fileEntries,
        projectSettings: {
          framework: "vite",
          buildCommand: "npm run build",
          installCommand: "npm install",
          outputDirectory: "dist",
        },
        target: "production",
      };

      // If linked to GitHub, use the project ID to deploy
      if (vercelProjectId) {
        deployPayload.project = vercelProjectId;
      }

      const deployRes = await fetch(`https://api.vercel.com/v13/deployments${teamQuery}`, {
        method: "POST",
        headers: { Authorization: `Bearer ${vToken}`, "Content-Type": "application/json" },
        body: JSON.stringify(deployPayload),
      });

      const deployData = await deployRes.json();

      if (!deployRes.ok) {
        const errMsg = deployData?.error?.message || JSON.stringify(deployData).slice(0, 300);
        console.error("[cirius-deploy] vercel deployment error:", errMsg);
        await logDeploy(sc, projectId, "deploy_vercel", "failed", `Vercel deploy error: ${errMsg.slice(0, 200)}`);
        return json({ error: `Vercel deployment failed: ${errMsg}` }, 500);
      }

      // Extract the real deployment URL
      const deploymentUrl = deployData.url
        ? (deployData.url.startsWith("http") ? deployData.url : `https://${deployData.url}`)
        : null;
      const inspectorUrl = deployData.inspectorUrl || null;
      const deploymentId = deployData.id || null;

      // Also get project-level production alias
      const aliasUrl = deployData.alias?.[0]
        ? `https://${deployData.alias[0]}`
        : `https://${projectSlug}.vercel.app`;

      const finalUrl = deploymentUrl || aliasUrl;

      await sc.from("cirius_projects").update({
        vercel_project_id: vercelProjectId,
        vercel_url: finalUrl,
        preview_url: finalUrl,
        status: "live",
        deployed_at: new Date().toISOString(),
      }).eq("id", projectId);

      await logDeploy(sc, projectId, "deploy_vercel", "completed",
        `Deploy live: ${finalUrl} (deployment: ${deploymentId})`);

      return json({
        deploy_url: finalUrl,
        deployment_url: deploymentUrl,
        deployment_id: deploymentId,
        inspector_url: inspectorUrl,
        status: "deployed",
      });
    } catch (e) {
      console.error("[cirius-deploy] vercel error:", (e as Error).message);
      await logDeploy(sc, projectId, "deploy_vercel", "failed", `Vercel deploy failed: ${(e as Error).message?.slice(0, 150)}`);
      return json({ error: "Vercel deploy failed" }, 500);
    }
  }

  // ─── NETLIFY ───
  if (action === "netlify") {
    const integration = await getIntegration(sc, projectUserId, "netlify");
    if (!integration?.access_token_enc) return json({ error: "Netlify not connected" }, 400);

    await logDeploy(sc, projectId, "deploy_netlify", "started", "Criando site Netlify...");

    try {
      const nToken = integration.access_token_enc;
      const siteName = project.name.toLowerCase().replace(/[^a-z0-9-]/g, "-").slice(0, 50);

      // Check if site already exists
      let siteId = project.netlify_site_id;
      if (!siteId) {
        const siteRes = await fetch("https://api.netlify.com/api/v1/sites", {
          method: "POST",
          headers: { Authorization: `Bearer ${nToken}`, "Content-Type": "application/json" },
          body: JSON.stringify({ name: siteName }),
        });
        const site = await siteRes.json();
        siteId = site.id;
      }

      // Deploy files via zip-less deploy (file digest)
      const fileDigests: Record<string, string> = {};
      for (const [path, content] of Object.entries(filesJson)) {
        if (typeof content !== "string") continue;
        // For Netlify, only deploy output files (index.html + assets)
        // Since this is source, we deploy as-is for static sites
        const sha = await sha1Hex(content);
        fileDigests[`/${path}`] = sha;
      }

      const deployRes = await fetch(`https://api.netlify.com/api/v1/sites/${siteId}/deploys`, {
        method: "POST",
        headers: { Authorization: `Bearer ${nToken}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          files: fileDigests,
          draft: false,
        }),
      });
      const deploy = await deployRes.json();

      // Upload required files
      if (deploy.required && deploy.required.length > 0) {
        for (const [path, content] of Object.entries(filesJson)) {
          if (typeof content !== "string") continue;
          const sha = await sha1Hex(content);
          if (deploy.required.includes(sha)) {
            await fetch(`https://api.netlify.com/api/v1/deploys/${deploy.id}/files/${encodeURIComponent(path)}`, {
              method: "PUT",
              headers: { Authorization: `Bearer ${nToken}`, "Content-Type": "application/octet-stream" },
              body: new TextEncoder().encode(content),
            });
          }
        }
      }

      const netlifyUrl = deploy.ssl_url || deploy.url || `https://${siteName}.netlify.app`;

      await sc.from("cirius_projects").update({
        netlify_site_id: siteId,
        netlify_url: netlifyUrl,
        preview_url: netlifyUrl,
        status: "live",
        deployed_at: new Date().toISOString(),
      }).eq("id", projectId);

      await logDeploy(sc, projectId, "deploy_netlify", "completed", `Site live: ${netlifyUrl}`);
      return json({ deploy_url: netlifyUrl, status: "deployed" });
    } catch (e) {
      console.error("[cirius-deploy] netlify error:", (e as Error).message);
      await logDeploy(sc, projectId, "deploy_netlify", "failed", "Netlify deploy failed");
      return json({ error: "Netlify deploy failed" }, 500);
    }
  }

  // ─── SUPABASE ───
  if (action === "supabase") {
    const integration = await getIntegration(sc, projectUserId, "supabase");
    if (!integration?.service_key_enc || !integration?.project_ref) {
      return json({ error: "Supabase not configured" }, 400);
    }

    await logDeploy(sc, projectId, "deploy_supabase", "started", "Aplicando migrations...");

    try {
      const migrations: string[] = [];
      for (const [path, content] of Object.entries(filesJson)) {
        if (path.startsWith("supabase/migrations/") && path.endsWith(".sql") && typeof content === "string") {
          migrations.push(content);
        }
      }

      if (migrations.length === 0) {
        await logDeploy(sc, projectId, "deploy_supabase", "completed", "Nenhuma migration encontrada");
        return json({ migrations_applied: 0, errors: [] });
      }

      const clientUrl = `https://${integration.project_ref}.supabase.co`;
      const errors: string[] = [];
      let applied = 0;

      for (const sql of migrations) {
        try {
          const clientSc = createClient(clientUrl, integration.service_key_enc);
          const { error: rpcErr } = await clientSc.rpc("exec_sql", { query: sql });
          if (rpcErr) throw new Error(rpcErr.message);
          applied++;
        } catch (e) {
          errors.push(`Migration failed: ${(e as Error).message?.slice(0, 100)}`);
        }
      }

      await sc.from("cirius_projects").update({
        supabase_project_id: integration.project_ref,
        supabase_url: clientUrl,
      }).eq("id", projectId);

      await logDeploy(sc, projectId, "deploy_supabase", applied > 0 ? "completed" : "failed",
        `${applied}/${migrations.length} migrations aplicadas`);

      return json({ migrations_applied: applied, errors });
    } catch (e) {
      console.error("[cirius-deploy] supabase error:", (e as Error).message);
      await logDeploy(sc, projectId, "deploy_supabase", "failed", "Supabase deploy failed");
      return json({ error: "Supabase deploy failed" }, 500);
    }
  }

  return json({ error: "unknown_action" }, 400);
});
