/**
 * Cirius Deploy — Handles GitHub, Vercel, Netlify, Supabase deploys
 * Actions: github, vercel, netlify, supabase
 */
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status, headers: { ...CORS, "Content-Type": "application/json" },
  });
}

async function getUser(req: Request) {
  const auth = req.headers.get("Authorization") || "";
  if (!auth.startsWith("Bearer ")) return null;
  const sc = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_ANON_KEY")!,
    { global: { headers: { Authorization: auth } } }
  );
  const { data: { user } } = await sc.auth.getUser();
  return user;
}

async function log(sc: ReturnType<typeof createClient>, projectId: string, step: string, status: string, message: string) {
  await sc.from("cirius_generation_log").insert({
    project_id: projectId, step, status, message,
    level: status === "failed" ? "error" : "info",
  });
}

async function getIntegration(sc: ReturnType<typeof createClient>, userId: string, provider: string) {
  const { data } = await sc.from("cirius_integrations")
    .select("*").eq("user_id", userId).eq("provider", provider).eq("is_active", true).maybeSingle();
  return data;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: CORS });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  const user = await getUser(req);
  if (!user) return json({ error: "Unauthorized" }, 401);

  const sc = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const body = await req.json().catch(() => ({}));
  const action = (body.action as string) || "";
  const projectId = (body.project_id as string) || "";

  if (!projectId) return json({ error: "project_id required" }, 400);

  const { data: project } = await sc.from("cirius_projects")
    .select("*").eq("id", projectId).eq("user_id", user.id).single();
  if (!project) return json({ error: "Project not found" }, 404);

  const filesJson = (project.source_files_json || {}) as Record<string, string>;
  if (Object.keys(filesJson).length === 0) return json({ error: "No source files to deploy" }, 400);

  await sc.from("cirius_projects").update({ status: "deploying" }).eq("id", projectId);

  // ─── GITHUB ───
  if (action === "github") {
    const integration = await getIntegration(sc, user.id, "github");
    if (!integration?.access_token_enc) return json({ error: "GitHub not connected. Connect via /cirius/settings." }, 400);

    const ghToken = integration.access_token_enc;
    const repoName = project.name.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-").slice(0, 50);

    await log(sc, projectId, "deploy_github", "started", "Criando repositório...");

    try {
      // Create repo
      const createRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: { Authorization: `Bearer ${ghToken}`, "Content-Type": "application/json", "User-Agent": "Cirius-Starble" },
        body: JSON.stringify({ name: repoName, private: false, auto_init: true, description: `Generated by Cirius — ${project.description || ""}` }),
      });

      let repoData: any;
      if (createRes.status === 422) {
        // Repo may already exist — try to get it
        const userRes = await fetch("https://api.github.com/user", {
          headers: { Authorization: `Bearer ${ghToken}`, "User-Agent": "Cirius-Starble" },
        });
        const userData = await userRes.json();
        const owner = userData.login;
        const getRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}`, {
          headers: { Authorization: `Bearer ${ghToken}`, "User-Agent": "Cirius-Starble" },
        });
        if (!getRes.ok) return json({ error: "Repo creation failed and existing not found" }, 500);
        repoData = await getRes.json();
      } else if (!createRes.ok) {
        const err = await createRes.json().catch(() => ({}));
        return json({ error: err.message || `GitHub ${createRes.status}` }, 500);
      } else {
        repoData = await createRes.json();
      }

      const owner = repoData.owner?.login || repoData.full_name?.split("/")[0];
      const repo = repoData.name;
      let pushed = 0;

      // Push files
      for (const [path, content] of Object.entries(filesJson)) {
        if (typeof content !== "string") continue;

        // Check if file exists
        const existRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}?ref=main`, {
          headers: { Authorization: `Bearer ${ghToken}`, "User-Agent": "Cirius-Starble" },
        });
        let sha: string | undefined;
        if (existRes.ok) {
          const existing = await existRes.json();
          sha = existing.sha;
        } else {
          await existRes.text().catch(() => {});
        }

        const putRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
          method: "PUT",
          headers: { Authorization: `Bearer ${ghToken}`, "Content-Type": "application/json", "User-Agent": "Cirius-Starble" },
          body: JSON.stringify({
            message: `feat: Cirius initial build — ${path}`,
            content: btoa(unescape(encodeURIComponent(content))),
            branch: "main",
            ...(sha ? { sha } : {}),
          }),
        });

        if (putRes.ok) pushed++;
        else await putRes.text().catch(() => {});
      }

      const repoUrl = `https://github.com/${owner}/${repo}`;
      await sc.from("cirius_projects").update({
        github_repo: `${owner}/${repo}`, github_url: repoUrl,
        status: "live", deployed_at: new Date().toISOString(),
      }).eq("id", projectId);

      await log(sc, projectId, "deploy_github", "completed", `${pushed} arquivos pushados para ${repoUrl}`);
      return json({ repo_url: repoUrl, files_pushed: pushed });
    } catch (e) {
      await log(sc, projectId, "deploy_github", "failed", (e as Error).message);
      return json({ error: (e as Error).message }, 500);
    }
  }

  // ─── VERCEL ───
  if (action === "vercel") {
    const integration = await getIntegration(sc, user.id, "vercel");
    if (!integration?.access_token_enc) return json({ error: "Vercel not connected" }, 400);

    const vToken = integration.access_token_enc;
    await log(sc, projectId, "deploy_vercel", "started", "Criando projeto Vercel...");

    try {
      // If github repo linked, use git deploy
      if (project.github_repo) {
        const createRes = await fetch("https://api.vercel.com/v9/projects", {
          method: "POST",
          headers: { Authorization: `Bearer ${vToken}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            name: project.name.toLowerCase().replace(/[^a-z0-9-]/g, "-").slice(0, 50),
            framework: "vite",
            gitRepository: { type: "github", repo: project.github_repo },
          }),
        });
        const vProject = await createRes.json();
        const deployUrl = vProject?.link?.deployHooks?.[0]?.url || `https://${vProject.name}.vercel.app`;

        await sc.from("cirius_projects").update({
          vercel_project_id: vProject.id, vercel_url: deployUrl,
        }).eq("id", projectId);

        await log(sc, projectId, "deploy_vercel", "completed", `Vercel linked to ${project.github_repo}`);
        return json({ deploy_url: deployUrl, status: "linked" });
      }

      return json({ error: "Deploy GitHub primeiro para conectar ao Vercel" }, 400);
    } catch (e) {
      await log(sc, projectId, "deploy_vercel", "failed", (e as Error).message);
      return json({ error: (e as Error).message }, 500);
    }
  }

  // ─── NETLIFY ───
  if (action === "netlify") {
    const integration = await getIntegration(sc, user.id, "netlify");
    if (!integration?.access_token_enc) return json({ error: "Netlify not connected" }, 400);

    await log(sc, projectId, "deploy_netlify", "started", "Criando site Netlify...");

    try {
      const nToken = integration.access_token_enc;
      const siteName = project.name.toLowerCase().replace(/[^a-z0-9-]/g, "-").slice(0, 50);

      // Create site
      const siteRes = await fetch("https://api.netlify.com/api/v1/sites", {
        method: "POST",
        headers: { Authorization: `Bearer ${nToken}`, "Content-Type": "application/json" },
        body: JSON.stringify({ name: siteName }),
      });
      const site = await siteRes.json();

      // For Netlify, we'd need to create a ZIP and deploy — simplified for now
      await sc.from("cirius_projects").update({
        netlify_site_id: site.id, netlify_url: site.ssl_url || site.url,
      }).eq("id", projectId);

      await log(sc, projectId, "deploy_netlify", "completed", `Site criado: ${site.ssl_url || site.url}`);
      return json({ deploy_url: site.ssl_url || site.url, status: "created" });
    } catch (e) {
      await log(sc, projectId, "deploy_netlify", "failed", (e as Error).message);
      return json({ error: (e as Error).message }, 500);
    }
  }

  // ─── SUPABASE ───
  if (action === "supabase") {
    const integration = await getIntegration(sc, user.id, "supabase");
    if (!integration?.service_key_enc || !integration?.project_ref) {
      return json({ error: "Supabase not configured. Add project URL and service key." }, 400);
    }

    await log(sc, projectId, "deploy_supabase", "started", "Aplicando migrations...");

    try {
      // Extract SQL migrations from files
      const migrations: string[] = [];
      for (const [path, content] of Object.entries(filesJson)) {
        if (path.startsWith("supabase/migrations/") && path.endsWith(".sql") && typeof content === "string") {
          migrations.push(content);
        }
      }

      if (migrations.length === 0) {
        await log(sc, projectId, "deploy_supabase", "completed", "Nenhuma migration encontrada");
        return json({ migrations_applied: 0, errors: [] });
      }

      const clientUrl = `https://${integration.project_ref}.supabase.co`;
      const errors: string[] = [];
      let applied = 0;

      for (const sql of migrations) {
        try {
          const clientSc = createClient(clientUrl, integration.service_key_enc);
          // Use rpc if available, otherwise skip
          await clientSc.rpc("exec_sql", { query: sql }).throwOnError();
          applied++;
        } catch (e) {
          errors.push((e as Error).message);
        }
      }

      await sc.from("cirius_projects").update({
        supabase_project_id: integration.project_ref,
        supabase_url: clientUrl,
      }).eq("id", projectId);

      await log(sc, projectId, "deploy_supabase", applied > 0 ? "completed" : "failed",
        `${applied}/${migrations.length} migrations aplicadas`);

      return json({ migrations_applied: applied, errors });
    } catch (e) {
      await log(sc, projectId, "deploy_supabase", "failed", (e as Error).message);
      return json({ error: (e as Error).message }, 500);
    }
  }

  return json({ error: "unknown_action" }, 400);
});
