/**
 * Cirius Deploy — Handles GitHub, Vercel, Netlify, Supabase deploys
 * Actions: github, vercel, netlify, supabase
 */
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status, headers: { ...CORS, "Content-Type": "application/json" },
  });
}

async function getUser(req: Request) {
  const auth = req.headers.get("Authorization") || "";
  if (!auth.startsWith("Bearer ")) return null;
  const sc = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_ANON_KEY")!,
    { global: { headers: { Authorization: auth } } }
  );
  const { data: { user } } = await sc.auth.getUser();
  return user;
}

async function logDeploy(sc: ReturnType<typeof createClient>, projectId: string, step: string, status: string, message: string) {
  await sc.from("cirius_generation_log").insert({
    project_id: projectId, step, status, message,
    level: status === "failed" ? "error" : "info",
  });
}

async function getIntegration(sc: ReturnType<typeof createClient>, userId: string, provider: string) {
  const { data } = await sc.from("cirius_integrations")
    .select("*").eq("user_id", userId).eq("provider", provider).eq("is_active", true).maybeSingle();
  return data;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: CORS });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  const user = await getUser(req);
  // Allow service-key calls for internal auto-deploy (from cirius-generate refine)
  const authHeader = req.headers.get("Authorization") || "";
  const isServiceKey = authHeader === `Bearer ${Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")}`;
  if (!user && !isServiceKey) return json({ error: "Unauthorized" }, 401);

  const sc = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const body = await req.json().catch(() => ({}));
  const action = (body.action as string) || "";
  const projectId = (body.project_id as string) || "";

  if (!projectId) return json({ error: "project_id required" }, 400);

  // When called via service key (internal), skip user_id filter
  let projectQuery = sc.from("cirius_projects").select("*").eq("id", projectId);
  if (user) projectQuery = projectQuery.eq("user_id", user.id);
  const { data: project } = await projectQuery.single();
  if (!project) return json({ error: "Project not found" }, 404);
  const projectUserId = project.user_id as string;

  const filesJson = (project.source_files_json || {}) as Record<string, string>;
  if (Object.keys(filesJson).length === 0) return json({ error: "No source files to deploy" }, 400);

  await sc.from("cirius_projects").update({ status: "deploying" }).eq("id", projectId);

  // ─── GITHUB ───
  if (action === "github") {
    const integration = await getIntegration(sc, projectUserId, "github");
    if (!integration?.access_token_enc) return json({ error: "GitHub not connected. Connect via integrations page." }, 400);

    const ghToken = integration.access_token_enc;
    const repoName = project.name.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-").slice(0, 50);

    await logDeploy(sc, projectId, "deploy_github", "started", "Criando repositório...");

    try {
      const createRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: { Authorization: `Bearer ${ghToken}`, "Content-Type": "application/json", "User-Agent": "Cirius-Starble" },
        body: JSON.stringify({ name: repoName, private: false, auto_init: true, description: `Generated by Cirius — ${project.description || ""}` }),
      });

      let repoData: any;
      if (createRes.status === 422) {
        const userRes = await fetch("https://api.github.com/user", {
          headers: { Authorization: `Bearer ${ghToken}`, "User-Agent": "Cirius-Starble" },
        });
        const userData = await userRes.json();
        const owner = userData.login;
        const getRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}`, {
          headers: { Authorization: `Bearer ${ghToken}`, "User-Agent": "Cirius-Starble" },
        });
        if (!getRes.ok) {
          await getRes.text().catch(() => {});
          return json({ error: "Repository creation failed" }, 500);
        }
        repoData = await getRes.json();
      } else if (!createRes.ok) {
        await createRes.text().catch(() => {});
        return json({ error: "Repository creation failed" }, 500);
      } else {
        repoData = await createRes.json();
      }

      const owner = repoData.owner?.login || repoData.full_name?.split("/")[0];
      const repo = repoData.name;
      let pushed = 0;

      for (const [path, content] of Object.entries(filesJson)) {
        if (typeof content !== "string") continue;

        const existRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}?ref=main`, {
          headers: { Authorization: `Bearer ${ghToken}`, "User-Agent": "Cirius-Starble" },
        });
        let sha: string | undefined;
        if (existRes.ok) {
          const existing = await existRes.json();
          sha = existing.sha;
        } else {
          await existRes.text().catch(() => {});
        }

        const putRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
          method: "PUT",
          headers: { Authorization: `Bearer ${ghToken}`, "Content-Type": "application/json", "User-Agent": "Cirius-Starble" },
          body: JSON.stringify({
            message: `feat: Cirius initial build — ${path}`,
            content: btoa(unescape(encodeURIComponent(content))),
            branch: "main",
            ...(sha ? { sha } : {}),
          }),
        });

        if (putRes.ok) pushed++;
        else await putRes.text().catch(() => {});
      }

      const repoUrl = `https://github.com/${owner}/${repo}`;
      await sc.from("cirius_projects").update({
        github_repo: `${owner}/${repo}`, github_url: repoUrl,
        status: "live", deployed_at: new Date().toISOString(),
        current_step: "done", progress_pct: 100,
        generation_ended_at: new Date().toISOString(),
      }).eq("id", projectId);

      await logDeploy(sc, projectId, "deploy_github", "completed", `${pushed} arquivos pushados para ${repoUrl}`);

      // Chain: auto-deploy to Vercel if integration is active
      const vercelIntegration = await getIntegration(sc, projectUserId, "vercel");
      if (vercelIntegration?.access_token_enc) {
        const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
        const svcKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
        fetch(`${supabaseUrl}/functions/v1/cirius-deploy`, {
          method: "POST",
          headers: { Authorization: `Bearer ${svcKey}`, "Content-Type": "application/json" },
          body: JSON.stringify({ action: "vercel", project_id: projectId }),
        }).catch(console.error);
      }

      return json({ repo_url: repoUrl, files_pushed: pushed });
    } catch (e) {
      console.error("[cirius-deploy] github error:", (e as Error).message);
      await logDeploy(sc, projectId, "deploy_github", "failed", "GitHub deploy failed");
      return json({ error: "GitHub deploy failed" }, 500);
    }
  }

  // ─── VERCEL ───
  if (action === "vercel") {
    const integration = await getIntegration(sc, projectUserId, "vercel");
    if (!integration?.access_token_enc) return json({ error: "Vercel not connected" }, 400);

    const vToken = integration.access_token_enc;
    await logDeploy(sc, projectId, "deploy_vercel", "started", "Criando projeto Vercel...");

    try {
      if (project.github_repo) {
        const createRes = await fetch("https://api.vercel.com/v9/projects", {
          method: "POST",
          headers: { Authorization: `Bearer ${vToken}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            name: project.name.toLowerCase().replace(/[^a-z0-9-]/g, "-").slice(0, 50),
            framework: "vite",
            gitRepository: { type: "github", repo: project.github_repo },
          }),
        });
        const vProject = await createRes.json();

        // Validate response before constructing URL
        if (!vProject || (!vProject.name && !vProject.id)) {
          const errMsg = vProject?.error?.message || JSON.stringify(vProject).slice(0, 200);
          await logDeploy(sc, projectId, "deploy_vercel", "failed", `Vercel API error: ${errMsg}`);
          return json({ error: `Vercel project creation failed: ${errMsg}` }, 500);
        }

        const vercelName = vProject.name || vProject.id || project.name.toLowerCase().replace(/[^a-z0-9-]/g, "-").slice(0, 50);
        const deployUrl = vProject?.link?.deployHooks?.[0]?.url || `https://${vercelName}.vercel.app`;

        await sc.from("cirius_projects").update({
          vercel_project_id: vProject.id, vercel_url: deployUrl,
        }).eq("id", projectId);

        await logDeploy(sc, projectId, "deploy_vercel", "completed", "Vercel linked");
        return json({ deploy_url: deployUrl, status: "linked" });
      }

      return json({ error: "Deploy GitHub primeiro para conectar ao Vercel" }, 400);
    } catch (e) {
      console.error("[cirius-deploy] vercel error:", (e as Error).message);
      await logDeploy(sc, projectId, "deploy_vercel", "failed", "Vercel deploy failed");
      return json({ error: "Vercel deploy failed" }, 500);
    }
  }

  // ─── NETLIFY ───
  if (action === "netlify") {
    const integration = await getIntegration(sc, projectUserId, "netlify");
    if (!integration?.access_token_enc) return json({ error: "Netlify not connected" }, 400);

    await logDeploy(sc, projectId, "deploy_netlify", "started", "Criando site Netlify...");

    try {
      const nToken = integration.access_token_enc;
      const siteName = project.name.toLowerCase().replace(/[^a-z0-9-]/g, "-").slice(0, 50);

      const siteRes = await fetch("https://api.netlify.com/api/v1/sites", {
        method: "POST",
        headers: { Authorization: `Bearer ${nToken}`, "Content-Type": "application/json" },
        body: JSON.stringify({ name: siteName }),
      });
      const site = await siteRes.json();

      await sc.from("cirius_projects").update({
        netlify_site_id: site.id, netlify_url: site.ssl_url || site.url,
      }).eq("id", projectId);

      await logDeploy(sc, projectId, "deploy_netlify", "completed", "Site criado");
      return json({ deploy_url: site.ssl_url || site.url, status: "created" });
    } catch (e) {
      console.error("[cirius-deploy] netlify error:", (e as Error).message);
      await logDeploy(sc, projectId, "deploy_netlify", "failed", "Netlify deploy failed");
      return json({ error: "Netlify deploy failed" }, 500);
    }
  }

  // ─── SUPABASE ───
  if (action === "supabase") {
    const integration = await getIntegration(sc, projectUserId, "supabase");
    if (!integration?.service_key_enc || !integration?.project_ref) {
      return json({ error: "Supabase not configured" }, 400);
    }

    await logDeploy(sc, projectId, "deploy_supabase", "started", "Aplicando migrations...");

    try {
      const migrations: string[] = [];
      for (const [path, content] of Object.entries(filesJson)) {
        if (path.startsWith("supabase/migrations/") && path.endsWith(".sql") && typeof content === "string") {
          migrations.push(content);
        }
      }

      if (migrations.length === 0) {
        await logDeploy(sc, projectId, "deploy_supabase", "completed", "Nenhuma migration encontrada");
        return json({ migrations_applied: 0, errors: [] });
      }

      const clientUrl = `https://${integration.project_ref}.supabase.co`;
      const errors: string[] = [];
      let applied = 0;

      for (const sql of migrations) {
        try {
          const clientSc = createClient(clientUrl, integration.service_key_enc);
          const { error: rpcErr } = await clientSc.rpc("exec_sql", { query: sql });
          if (rpcErr) throw new Error(rpcErr.message);
          applied++;
        } catch (e) {
          errors.push(`Migration failed: ${(e as Error).message?.slice(0, 100)}`);
        }
      }

      await sc.from("cirius_projects").update({
        supabase_project_id: integration.project_ref,
        supabase_url: clientUrl,
      }).eq("id", projectId);

      await logDeploy(sc, projectId, "deploy_supabase", applied > 0 ? "completed" : "failed",
        `${applied}/${migrations.length} migrations aplicadas`);

      return json({ migrations_applied: applied, errors });
    } catch (e) {
      console.error("[cirius-deploy] supabase error:", (e as Error).message);
      await logDeploy(sc, projectId, "deploy_supabase", "failed", "Supabase deploy failed");
      return json({ error: "Supabase deploy failed" }, 500);
    }
  }

  return json({ error: "unknown_action" }, 400);
});
